# NAME: Zhonglin Zhang
# EMAIL: evanzhang@ucla.edu
# ID: 005030520

default: lab1a.c
	gcc -g -Wall -Wextra -o lab1a lab1a.c

clean:
	rm -rf lab1a *.tar.gz

dist:
	tar -zcvf "lab1a-005030520.tar.gz" lab1a.c Makefile README

